### PR TITLE
Better handling of map_odom on param server

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by jlunenburg** [comment]
So you use the initial pose from the parameter server even if an initial pose is provided? Is `map_odom` the clearest parameter description? If someone would read it (it's listed on the parameter server), would he/she know what it means?

**Comment by MatthijsBurgh** [comment]
`map_odom` may indeed not be the clearest name.

In the current situation, if the parameter is available, the config is ignored. But if anything in between fails, than both pose from the parameter and the config isn't used/
So this PR doesn't change the priority, but if the processing of the pose from the parameter fails than the config is still used.

**Comment by MatthijsBurgh** [comment]
@jlunenburg ping ;)

**Comment by MatthijsBurgh** [comment]
@jlunenburg , you made one small mistake. That is now fixed. I have tested starting the plugin with pose on the parameter server, without parameter server, but with config and no initial pose at all. Everything works now.

**Review by jlunenburg — APPROVED** [review]
Next time we'll add a corresponding test (would need more refactoring) but I think we've already improved a lot ;-)

**Pull request merged**
