### PR TITLE
fix rotation of initial pose

### PR DESCRIPTION
**Pull request by PetervDooren**
Taking into account the feedback given in #26

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Are you sure these angles are correct?

**Comment by PetervDooren** [comment]
Tested in simulation. I am fairly sure but it would be good to test this. I am also sure that the current implementation is indeed broken. Just send a pose estimate towards the soccer field

**Comment by MatthijsBurgh** [comment]
Yes I experience the issue with the old implementation. I will test your solution too layer today.

**Review by MatthijsBurgh — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
Tested and it indeed works.

**Pull request merged**
