### PR TITLE
Feature/remember pose

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
In simulator it works when only free-mode is restarted, because the lasers are not updated correct. This is not a problem on the robot. As long as roscore stays on, it should work.

### CODE REVIEW

**Comment by reinzor** [comment]
Tested on robot?

**Comment by rokusottervanger** [comment]
Can you explain why it works differently in simulation?

**Comment by MatthijsBurgh** [comment]
Not tested yet.

In the simulator the lasers are simulated. These are not updated when the pose is set. This is the part where it is not working. On the robot the laserpoints will always be on the correct place.

So when only free-mode is restarted, the fast-simulator is not shutdown, then it does work.

**Comment by reinzor** [comment]
Tested and fixed on robot

**Review by reinzor — APPROVED** [review]

**Pull request merged**
